=== Mouna48/Zinemaldi_Compartido/SalaReto/SalaReto/Sala.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Elemento raíz -->
    <xs:element name="Salas">
        <xs:complexType>
            <xs:sequence>
                <!-- Una o más salas -->
                <xs:element name="Sala" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <!-- Nombre obligatorio de tipo string -->
                            <xs:element name="Nombre" type="xs:string" />
                            <!-- Capacidad obligatoria de tipo entero -->
                            <xs:element name="Capacidad" type="xs:int" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Mouna48/Zinemaldi_Compartido/SalaReto/SalaReto/Sala.xml
<?xml version="1.0" encoding="UTF-8"?>
<Salas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="Sala.xsd">
    <Sala>
        <Nombre>Kursaal 1</Nombre>
        <Capacidad>1800</Capacidad>
    </Sala>
    <Sala>
        <Nombre>Kursaal 2</Nombre>
        <Capacidad>600</Capacidad>
    </Sala>
    <Sala>
        <Nombre>Teatro Victoria Eugenia</Nombre>
        <Capacidad>900</Capacidad>
    </Sala>
    <Sala>
        <Nombre>Sala Principal ABC</Nombre>
        <Capacidad>500</Capacidad>
    </Sala>
    <Sala>
        <Nombre>Sala Experimental XYZ</Nombre>
        <Capacidad>250</Capacidad>
    </Sala>
</Salas>
