=== Mouna48/Zinemaldi_Compartido/peliculas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="peliculas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="pelicula" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="IDPelicula" type="xs:int"/>
              <xs:element name="Titulo" type="xs:string"/>
              <xs:element name="Sinopsis" type="xs:string" minOccurs="0"/>
              <xs:element name="Director" type="xs:string" minOccurs="0"/>
              <xs:element name="Duracion" type="xs:int"/>
              <xs:element name="Genero" type="xs:string" minOccurs="0"/>
              <xs:element name="AÃ±oLanzamiento" type="xs:gYear" minOccurs="0"/>
              <xs:element name="Pais" type="xs:string" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Mouna48/Zinemaldi_Compartido/Peli reto/Peli reto/Pelicula.xml
<?xml version="1.0" encoding="UTF-8"?>
<peliculas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="peliculas.xsd">

    <pelicula>
        <IDPelicula>1</IDPelicula>
        <Titulo>Los domingos</Titulo>
        <Sinopsis>Una historia sobre la vida dominical de una familia española.</Sinopsis>
        <Director>Alauda Ruiz de Azúa</Director>
        <Duracion>115</Duracion>
        <Genero>Drama</Genero>
        <AñoLanzamiento>2025</AñoLanzamiento>
        <Pais>España</Pais>
    </pelicula>
    <pelicula>
        <IDPelicula>2</IDPelicula>
        <Titulo>Los Tigres</Titulo>
        <Sinopsis>Thriller criminal ambientado en España.</Sinopsis>
        <Director>Alberto Rodríguez</Director>
        <Duracion>120</Duracion>
        <Genero>Thriller</Genero>
        <AñoLanzamiento>2025</AñoLanzamiento>
        <Pais>España</Pais>
    </pelicula>
    <pelicula>
        <IDPelicula>3</IDPelicula>
        <Titulo>Maspalomas</Titulo>
        <Sinopsis>Drama que narra la vida de un pequeño pueblo en Canarias.</Sinopsis>
        <Director>Jose Mari Goenaga</Director>
        <Duracion>105</Duracion>
        <Genero>Drama</Genero>
        <AñoLanzamiento>2025</AñoLanzamiento>
        <Pais>España</Pais>
    </pelicula>
    <pelicula>
        <IDPelicula>4</IDPelicula>
        <Titulo>Historias del buen valle</Titulo>
        <Sinopsis>Documental sobre las costumbres y tradiciones del Valle.</Sinopsis>
        <Director>José Luis Guerín</Director>
        <Duracion>130</Duracion>
        <Genero>Documental</Genero>
        <AñoLanzamiento>2025</AñoLanzamiento>
        <Pais>España</Pais>
    </pelicula>

    <pelicula>
        <IDPelicula>5</IDPelicula>
        <Titulo>Nuremberg</Titulo>
        <Sinopsis>Película histórica sobre los juicios de Nuremberg.</Sinopsis>
        <Director>James Vanderbilt</Director>
        <Duracion>138</Duracion>
        <Genero>Histórico</Genero>
        <AñoLanzamiento>2025</AñoLanzamiento>
        <Pais>Estados Unidos</Pais>
    </pelicula>

    <pelicula>
        <IDPelicula>6</IDPelicula>
        <Titulo>La Cri des Gardes</Titulo>
        <Sinopsis>Drama francés sobre conflictos familiares.</Sinopsis>
        <Director>Claire Denis</Director>
        <Duracion>112</Duracion>
        <Genero>Drama</Genero>
        <AñoLanzamiento>2025</AñoLanzamiento>
        <Pais>Francia</Pais>
    </pelicula>

</peliculas>

=== Mouna48/Zinemaldi_Compartido/Pelicula.xml
<?xml version="1.0" encoding="UTF-8"?>
<peliculas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="peliculas.xsd">
    <pelicula>
        <IDPelicula>1</IDPelicula>
        <Titulo>El Origen</Titulo>
        <Sinopsis>Un hombre explora los sueños y la realidad.</Sinopsis>
        <Director>Christopher Nolan</Director>
        <Duracion>148</Duracion>
        <Genero>Ciencia Ficción</Genero>
        <AñoLanzamiento>2010</AñoLanzamiento>
        <Pais>USA</Pais>
    </pelicula>
    <pelicula>
        <IDPelicula>2</IDPelicula>
        <Titulo>Parásitos</Titulo>
        <Sinopsis>Una familia pobre se infiltra en la vida de otra rica.</Sinopsis>
        <Director>Bong Joon-ho</Director>
        <Duracion>132</Duracion>
        <Genero>Thriller</Genero>
        <AñoLanzamiento>2019</AñoLanzamiento>
        <Pais>Corea del Sur</Pais>
    </pelicula>
    <pelicula>
        <IDPelicula>3</IDPelicula>
        <Titulo>Amélie</Titulo>
        <Sinopsis>La vida mágica de una joven en París.</Sinopsis>
        <Director>Jean-Pierre Jeunet</Director>
        <Duracion>122</Duracion>
        <Genero>Comedia Romántica</Genero>
        <AñoLanzamiento>2001</AñoLanzamiento>
        <Pais>Francia</Pais>
    </pelicula>
    <pelicula>
        <IDPelicula>4</IDPelicula>
        <Titulo>La La Land</Titulo>
        <Sinopsis>Historia de amor y música en Los Ángeles.</Sinopsis>
        <Director>Damien Chazelle</Director>
        <Duracion>128</Duracion>
        <Genero>Musical</Genero>
        <AñoLanzamiento>2016</AñoLanzamiento>
        <Pais>USA</Pais>
    </pelicula>
    <pelicula>
        <IDPelicula>5</IDPelicula>
        <Titulo>Roma</Titulo>
        <Sinopsis>Una familia en México en los años 70.</Sinopsis>
        <Director>Alfonso Cuarón</Director>
        <Duracion>135</Duracion>
        <Genero>Drama</Genero>
        <AñoLanzamiento>2018</AñoLanzamiento>
        <Pais>México</Pais>
    </pelicula>
</peliculas>
